---
repos:
  # update the rev versions with a `pre-commit autoupdate`
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --expand-star-imports
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --recursive
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.1
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: ^notebooks/
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        args: [--safe, --quiet]
        exclude: ^notebooks/
  # - repo: https://github.com/pycqa/flake8
  #   rev: "4.0.1"
  #   hooks:
  #     - id: flake8
  #       exclude: ^notebooks/
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.11
    hooks:
      - id: mdformat
        # Optionally add plugins
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
