---
repos:
  # update the rev versions with a `pre-commit autoupdate`
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.19.0
      hooks:
          - id: pyupgrade
            args: [--py38-plus]
    - repo: https://github.com/myint/autoflake
      rev: v2.3.1
      hooks:
          - id: autoflake
            args:
                - --in-place
                - --expand-star-imports
                - --remove-all-unused-imports
                - --remove-unused-variables
                - --recursive
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v3.1.0
      hooks:
          - id: add-trailing-comma
            args: [--py36-plus]
    - repo: https://github.com/PyCQA/isort
      rev: 5.13.2
      hooks:
          - id: isort
            exclude: ^notebooks/
    - repo: https://github.com/psf/black
      rev: 24.10.0
      hooks:
          - id: black
            args: [--safe, --quiet]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
    - repo: https://github.com/adrienverge/yamllint
      rev: v1.35.1
      hooks:
          - id: yamllint
            name: yamllint
            description: This hook runs yamllint.
            entry: yamllint
            language: python
            types: [file, yaml]
